### ISSUE TITLE
social keys for env is being required for bare search (search engines)

### ISSUE THREAD

**Issue by Preshy** [L4ser-Security-Labs/whoget#2]
Traceback (most recent call last):
  File "whoget.py", line 29, in <module>
    import social
  File "src/social.py", line 31, in <module>
    TWITTER_API_KEY=config('TWITTER_API_KEY')
  File "/usr/local/lib/python3.7/site-packages/decouple.py", line 199, in __call__
    return self.config(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/decouple.py", line 83, in __call__
    return self.get(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/decouple.py", line 68, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: TWITTER_API_KEY not found. Declare it as envvar or define a default value.

**Comment by lagosnomad** [comment]
Hi, have you created your `.env` file?

Please check the API Keys Setup in the README
https://github.com/L4ser-Security-Labs/whoget/blob/master/README.md#setup-api-keys

**Comment by Preshy** [comment]
🤲🏿
